/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.MesaCamareroDAO;
import net.proteanit.sql.DbUtils;
import controlador.UsuarioDAO;
import extras.Mensajes;

import java.sql.ResultSet;

import java.util.Date;
import javax.swing.JComboBox;
import modelo.MesaCamarero;


public class IfrmConfiguracionMesas extends javax.swing.JInternalFrame {

    public IfrmConfiguracionMesas() {
        initComponents();

        ResultSet rsE;
        rsE = UsuarioDAO.getDataEmpleadoCamarero();
        ResultSet rsMesa;
        rsMesa = MesaCamareroDAO.getDataNumeroMesas();
        cargarcomboEmpleado(cboEmpleado, rsE);
        cargarcomboMesas(cboMesa,rsMesa);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblConfiguracion = new javax.swing.JTable();
        cboMesa = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btngrabar = new javax.swing.JButton();
        cboEmpleado = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btncancelar = new javax.swing.JButton();
        jdateFechaInicio = new com.toedter.calendar.JDateChooser();
        jdateFechaFin = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jdateFechaIniciob = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jdateFechaFinb = new com.toedter.calendar.JDateChooser();
        btnBuscar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Sistema de ventas SVA 1.1 / Formulario Configuración Mesas");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        tblConfiguracion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblConfiguracion);

        jLabel4.setText("Fecha fin:");

        jLabel2.setText("Fecha inicio:");

        jLabel3.setText("Elija Mesa:");

        btngrabar.setText("Grabar");
        btngrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngrabarActionPerformed(evt);
            }
        });

        jLabel5.setText("Camarero:");

        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        jdateFechaInicio.setDateFormatString("dd-MM-yyyy");

        jdateFechaFin.setDateFormatString("dd-MM-yyyy");

        jLabel6.setText("Fecha inicio:");

        jdateFechaIniciob.setDateFormatString("dd-MM-yyyy");

        jLabel7.setText("Fecha fin:");

        jdateFechaFinb.setDateFormatString("dd-MM-yyyy");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jdateFechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(cboMesa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdateFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btngrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jdateFechaIniciob, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jdateFechaFinb, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btngrabar)
                            .addComponent(btncancelar)
                            .addComponent(jLabel6)
                            .addComponent(btnBuscar))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jdateFechaFinb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jdateFechaIniciob, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cboEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jdateFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdateFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        listarConfiguracionMesas();

    }//GEN-LAST:event_formInternalFrameOpened

    private void btngrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngrabarActionPerformed

        if (validarcampos()) {
            grabar();
            listarConfiguracionMesas();
            limpiar();
        } else {
            Mensajes.msjmuestra("Ingrese rango de fechas valido");
        }

    }//GEN-LAST:event_btngrabarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
       cerrarVentana();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        if (validarcamposBusqueda()) {
            
            listarConfiguracionMesasByFechas(jdateFechaIniciob.getDate(),jdateFechaFinb.getDate());
        } else {
            Mensajes.msjmuestra("Ingrese rango de fechas valido");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    public void listarConfiguracionMesas() {
        try {
            tblConfiguracion.setModel(DbUtils.resultSetToTableModel(MesaCamareroDAO.getDataMesaCamarero()));
        } catch (Exception e) {
            Mensajes.msjmuestra("Error View al listar!!!");
        }
    }
    public void listarConfiguracionMesasByFechas(Date inicio,Date fin) {
        try {
            tblConfiguracion.setModel(DbUtils.resultSetToTableModel(MesaCamareroDAO.getDataMesaCamareroByInicioFin(inicio,fin)));
        } catch (Exception e) {
            Mensajes.msjmuestra("Error View al listar!!!");
        }
    }
    public void grabar() {

        try {

            MesaCamarero omc = new MesaCamarero();
            omc.setNumMesa(Integer.parseInt(cboMesa.getSelectedItem().toString()));
            omc.setEmpleadoId(UsuarioDAO.getIDempleadoxNombre(cboEmpleado.getSelectedItem().toString()));
            omc.setFechaInicio(jdateFechaInicio.getDate());
            omc.setFechaFin(jdateFechaFin.getDate());
            if (MesaCamareroDAO.grabarConfiguracionMesaCamarero(omc) == true) {
                Mensajes.msjmuestra("Grabado Correctamente!!!");
            }
        } catch (Exception e) {
            Mensajes.msjmuestra("Error View al grabar!!!");
        }

    }

    public static void cargarcomboMesas(JComboBox combo,ResultSet rs) {
       try {
            while (rs.next()) {
                combo.addItem(rs.getString("numMesa"));
            }
            rs.close();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }

    public static void cargarcomboEmpleado(JComboBox combo, ResultSet rs) {
        try {
            while (rs.next()) {
                combo.addItem(rs.getString("nombres"));
            }
            rs.close();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }

    public void limpiar() {

        cboMesa.setSelectedIndex(0);
        cboEmpleado.setSelectedIndex(0);
    }

    public boolean validarcampos() {
        if (jdateFechaInicio.getDate() == null) {
            return false;       
        }
        if (jdateFechaFin.getDate() == null) {
            return false;       
        }
        return true;
    }
     public boolean validarcamposBusqueda() {
        if (jdateFechaIniciob.getDate() == null) {
            return false;       
        }
        if (jdateFechaFinb.getDate() == null) {
            return false;       
        }
        return true;
    }

    void cerrarVentana() {
        this.dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btngrabar;
    private javax.swing.JComboBox<String> cboEmpleado;
    private javax.swing.JComboBox<String> cboMesa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdateFechaFin;
    private com.toedter.calendar.JDateChooser jdateFechaFinb;
    private com.toedter.calendar.JDateChooser jdateFechaInicio;
    private com.toedter.calendar.JDateChooser jdateFechaIniciob;
    private javax.swing.JTable tblConfiguracion;
    // End of variables declaration//GEN-END:variables
}
