/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.DetallePedidoDAO;
import net.proteanit.sql.DbUtils;

import controlador.NotaPedidoDAO;
import controlador.UsuarioDAO;
import extras.Mensajes;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


public class IfrmPedidosPendientes extends javax.swing.JInternalFrame {
    
    int idEmpleado;
    DefaultTableModel mdl = new DefaultTableModel();

    public IfrmPedidosPendientes() {
        initComponents();
        //de aqui es para la lista doble click
        tblDetallePedido.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent Mouse_evt) {
                JTable table = (JTable) Mouse_evt.getSource();
                Point point = Mouse_evt.getPoint();
                int row = table.rowAtPoint(point);
                if (Mouse_evt.getClickCount() == 1) {
                    pasarDatosFila();
                }
            }
        });
        //finaliza

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetallePedido = new javax.swing.JTable();
        btnRefrescar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lblCamarero = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbldata = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Sistema de ventas SVA 1.1 / Formulario de Pedidos de cocina");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        tblDetallePedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblDetallePedido.setGridColor(new java.awt.Color(255, 204, 102));
        tblDetallePedido.setRowHeight(20);
        jScrollPane1.setViewportView(tblDetallePedido);

        btnRefrescar.setText("Refrescar Lista");
        btnRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarActionPerformed(evt);
            }
        });

        jLabel9.setText("Camarero:");

        lblCamarero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tbldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbldata);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRefrescar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCamarero, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1073, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRefrescar)
                        .addComponent(jLabel9))
                    .addComponent(lblCamarero, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void cabeceraDetalle() {
        tbldata.setModel(mdl);
        mdl.addColumn("CODIGO");
        mdl.addColumn("DESCRIPCION");
        mdl.addColumn("PRECIO");
        mdl.addColumn("CANTIDAD");
        mdl.addColumn("IMPORTE");
        mdl.addColumn("ESTADO");

    }
    public void pasarDatosFila() {
        if (tblDetallePedido.isEnabled()) {
            int filaseleccionada = tblDetallePedido.getSelectedRow();
            int numpedido = (int) tblDetallePedido.getValueAt(filaseleccionada, 0);
            mdl.setRowCount(0);
            mdl.setColumnCount(0);
            this.cabeceraDetalle();
            this.llenandoDetalle(numpedido);

        }

    }

    private void llenandoDetalle(int numpedi) {

        try {
            ResultSet rs = DetallePedidoDAO.getDetallePedidoEmitidoByNumeroPedido(numpedi);
            int column = 6;
            Object data[] = new Object[column];
            while (rs.next()) {
                for (int i = 0; i < column; i++) {
                    data[i] = rs.getString(i + 1);
                }
                mdl.addRow(data);
            }

        } catch (Exception e) {
            Mensajes.msjmuestra("Error al obtener los detalles del comprobante " + e.getMessage());
        }
    }

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
       
        FrmLogin oa = new FrmLogin();
        String nombreUsuario = oa.nombUsu;
        lblCamarero.setText(UsuarioDAO.getNombreCamareroByNombreUsuario(nombreUsuario));
        idEmpleado = UsuarioDAO.getIDempleadoxNombre(lblCamarero.getText());
        listarPedidosSolicitados(idEmpleado);
        this.cabeceraDetalle();
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed
      
        listarPedidosSolicitados(idEmpleado);

    }//GEN-LAST:event_btnRefrescarActionPerformed

    public void listarPedidosSolicitados(int idEmpleado) {
        try {
            tblDetallePedido.setModel(DbUtils.resultSetToTableModel(NotaPedidoDAO.getPedidosPendientesByCamarero(idEmpleado)));
        } catch (Exception e) {
            Mensajes.msjmuestra("Error View al listar carta!!!");
        }
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCamarero;
    private javax.swing.JTable tblDetallePedido;
    private javax.swing.JTable tbldata;
    // End of variables declaration//GEN-END:variables
}
