/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import extras.Mensajes;
import javax.swing.JOptionPane;
import org.codehaus.groovy.control.messages.Message;
import controlador.UsuarioDAO;
import modelo.Usuario;

/**
 *
 * @author Padin
 */
public class IfrmmntUsuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrmmntUsuarios
     */
    public IfrmmntUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtcod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtusu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtpass = new javax.swing.JTextField();
        cborol = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnnuevo = new javax.swing.JButton();
        btnactualizaR = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        chbest = new javax.swing.JCheckBox();
        btnbuscar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("Codigo:");

        jLabel2.setText("Usuario:");

        jLabel3.setText("Rol:");

        cborol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Administrador", "Estandar" }));

        jLabel4.setText("Password:");

        btnnuevo.setText("Grabar");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        btnactualizaR.setText("Actualizar");
        btnactualizaR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizaRActionPerformed(evt);
            }
        });

        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        chbest.setText("Activo");

        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtpass)
                            .addComponent(txtusu)
                            .addComponent(cborol, 0, 221, Short.MAX_VALUE)
                            .addComponent(txtcod))
                        .addGap(33, 33, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnnuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnactualizaR, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(btneliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnbuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chbest, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnnuevo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtusu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnactualizaR))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btneliminar)
                    .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cborol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar))
                .addGap(18, 18, 18)
                .addComponent(chbest)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        
        try {
        //Campos de tipo Objeto
        int est=0;
        Usuario ou=new Usuario();
        ou.setUsuario(txtusu.getText());
        ou.setPassword(txtpass.getText());
        ou.setRol(cborol.getSelectedItem().toString());
//        if(chbest.isSelected()){
//            est=1;
//        }
//        ou.setEstado(est);
        if(UsuarioDAO.newusuario(ou)==true){
            Mensajes.msjmuestra("Grabado Correctamente!!!");
            this.Limpiar();
        }
        } catch (Exception e) {
            Mensajes.msjmuestra("Error View al grabar!!!");
        }
        
        
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
       txtcod.setText(""+UsuarioDAO.generarCodUsuario());
       txtcod.setEditable(false);
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
         Usuario ou=new Usuario();
        
         try {
             String buscar=Mensajes.miInput("Codigo de usuario");
        int codigo=Integer.parseInt(buscar);
        ou=UsuarioDAO.getUsuarioByID(codigo);
        
       
             txtcod.setText(""+ou.getUsuarioId());
        txtusu.setText(ou.getUsuario());
        txtpass.setText(ou.getPassword());
        if(ou.getRol().equals("Administrador")){
            cborol.setSelectedIndex(1);
            }else{
            cborol.setSelectedIndex(2);
        }
        
//        if(ou.getEstado()==1){
//            chbest.setSelected(true);
//        }else{
//            chbest.setSelected(false);
//        }
          
       
        } catch (Exception e) {
            Mensajes.msjmuestra("Codigo de usuario no Registrado:" +e.getMessage());
        }
         
       
        
        
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnactualizaRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizaRActionPerformed
         try {
        //Campos de tipo Objeto
        int est=0;
        Usuario ou=new Usuario();
        ou.setUsuario(txtusu.getText());
        ou.setPassword(txtpass.getText());
        ou.setRol(cborol.getSelectedItem().toString());
//        if(chbest.isSelected()){
//            est=1;
//        }
//        ou.setEstado(est);
         ou.setUsuarioId(Integer.parseInt(txtcod.getText()));
        if(UsuarioDAO.actualizarUsuario(ou)==true){
            Mensajes.msjmuestra("Actualizado Correctamente!!!");
            this.Limpiar();
        }
        } catch (Exception e) {
            Mensajes.msjmuestra("Error View al Actualizado!!!");
        }
        
    }//GEN-LAST:event_btnactualizaRActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
         try {
        //Campos de tipo Objeto
        int est=0;
        int codigo =Integer.parseInt(txtcod.getText());
        if(UsuarioDAO.deleteUsuario(codigo)==true){
            Mensajes.msjmuestra("Eliminado Correctamente!!!");
            this.Limpiar();
        }
        } catch (Exception e) {
            Mensajes.msjmuestra("Error View al Eliminado!!!");
        }
        
    }//GEN-LAST:event_btneliminarActionPerformed

    
    private void Limpiar(){
        txtcod.setText("");
        txtpass.setText("");
        txtusu.setText("");
        cborol.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizaR;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JComboBox<String> cborol;
    private javax.swing.JCheckBox chbest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtcod;
    private javax.swing.JTextField txtpass;
    private javax.swing.JTextField txtusu;
    // End of variables declaration//GEN-END:variables
}
